// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnjmaybhricwuuuqvnun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuam1heWJocmljd3V1dXF2bnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM1NjEsImV4cCI6MjA2NTQ2OTU2MX0.d2m6X8mVteVRyscc1_hwJt8h-TkZqNXbMIQxnyIH9Sk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);